Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Controllers/RacaController.cs
using Entra21.CSharp.ClinicaVeterinaria.Repositorio.BancoDados;
using Entra21.CSharp.ClinicaVeterinaria.Repositorio.Enum;
using Entra21.CSharp.ClinicaVeterinaria.Servico;
using Entra21.CSharp.ClinicaVeterinaria.Servico.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Entra21.CSharp.ClinicaVeterinaria.Aplicacao.Controllers
{
    public class RacaController : Controller
    {

        private readonly IRacaServico _racaService;


        // Contrutor: objetivo contruir o objeto de RacaController,
        //com o minimo necessario para o funcionamenro correto
        public RacaController(ClinicaVeterinariaContexto contexto)
        {
            _racaService = new RacaServico(contexto);

        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        //[Route("/raca")]
        [HttpGet("/raca")]
        /// Endpoist que  permite listar todas as raças
        /// <returns> Retorna a página hyml com as raças </returns>>
        public IActionResult ObterTodos()
        {
            var racas = _racaService.ObterTodos();

            // Passar informacao do c# para o HTML
            return View("Index", racas);
        }

        private List<string> ObterEspecies()
        {
            return Enum.GetNames<Especie>().OrderBy(x => x).ToList();
        }

        //[Route("/raca/cadastrar")]
        [HttpGet("/raca/cadastrar")]
        public IActionResult Cadastrar()
        {
            var especies = ObterEspecies();
            ViewBag.Especies = especies;

            var racaCadastrarViewModel = new RacaCadastrarViewModel();

            return View(racaCadastrarViewModel);
        }

        //[Route("/raca/cadastrar")]
        [HttpPost("/raca/cadastrar")]

        // TODO ModelState
        public IActionResult Cadastrar(
            [FromForm]RacaCadastrarViewModel racaCadastrarViewModel)
        {
            
            if (!ModelState.IsValid)
            {
                ViewBag.Especies = ObterEspecies();

                return View(racaCadastrarViewModel);
            }
            
            _racaService.Cadastrar(racaCadastrarViewModel);

            return RedirectToAction("Index");
        }

        //[Route("/raca/apagar")]
        [HttpGet("/raca/apagar")]

        public IActionResult Apagar([FromQuery] int id)
        {
            _racaService.Apagar(id);

            return RedirectToAction("Index");
        }

        [HttpGet("/raca/editar")]
        //[Route("/raca/editar")]

        public IActionResult Editar([FromQuery] int id)
        {
            var raca = _racaService.ObterPorId(id);
            var especies = ObterEspecies();

            ViewBag.Raca = raca;
            ViewBag.Especie = especies;

            return View("Editar");
        }

        [HttpPost("/raca/editar")]
        //[Route("/raca/editar")]
        public IActionResult Editar(
            [FromForm] RacaEditarViewModel racaEditarViewModel)
        {
            _racaService.Editar(racaEditarViewModel);

            return RedirectToAction("Index");
        }

    }
}

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Entra21.CSharp.ClinicaVeterinaria.Aplicacao.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Entra21.CSharp.ClinicaVeterinaria.Aplicacao.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Entra21.CSharp.ClinicaVeterinaria.Aplicacao.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Entra21.CSharp.ClinicaVeterinaria.Aplicacao</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Entra21.CSharp.ClinicaVeterinaria.Aplicacao.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CV SOS Irmãos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Raca" asp-action="Index">Raças</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Entra21.CSharp.ClinicaVeterinaria.Aplicacao - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Views/Raca/Cadastrar.cshtml
@model Entra21.CSharp.ClinicaVeterinaria.Servico.ViewModels.RacaCadastrarViewModel

@{
    var especies = ViewBag.Especies as List<string>;
    especies.Add(string.Empty);

    var selectDasEspecies = new SelectList(especies, string.Empty);
}

<h3>Cadastro da Raça</h3>

<form asp-action="cadastrar" method="POST">

    <div class="mb-3">
        <label asp-for="Nome" class="form-labol" />
        <input asp-for="Nome" class="form-label" required="required" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Especie" class="form-label"></label>
        <select asp-for="Especie" asp-items="selectDasEspecies" class="form-select"> </select>
        <span asp-validation-for="Especie" class="text-danger"></span>
    </div>

    <div class="text-end">
        <a href="/raca" class="btn btn-outline-danger">Canselar</a>
        <button type="submit" class="btn btn-success">Salvar</button>
    </div>
</form>

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Views/Raca/Editar.cshtml
@*@using Entra21.CSharp.ClinicaVeterinaria.Repositorio.Entidades
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
    var raca = ViewBag.Raca as Raca;
    var especies = ViewBag.Especies as List<string>;
}

<h3>Editar da Raça</h3>

<form action="/raca/edirar" method="POST">
    <input type="hidden" name="id" value="@raca.Id"
    
    <div class="mb-3">
        <label for="campo_nome" class="form-labol">Nome<span class="text-danger fm-bold">*</span></label>
        <input type="text" id="campo_nome" name="nome" class="form-label" required="required" 
        value="@raca.Nome"/>
    </div>

    <div class="mb-3">
        <label for="campo_esoecie" class="form-label">Espécie<span class="text-danger fm-bold">*</span></label>
        <select id="campo_especie" name="especie" class="form-select" required="required" required="requiered">
        @foreach(var especie in especies)
            {
                <option value="@especie" @(especie == raca.Especie ? "Selected" : "")>@especie</option>
            }
            <option value="Gato">Gato</option>
        </select>
    </div>

    <div class="text-end">
        <a href="/raca" class="btn btn-outline-danger">Canselar</a>
        <button type="submit" class="btn btn-success">Salvar</button>
    </div>
</form>*@

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Views/Raca/Index.cshtml
@model List<Raca>

<h1>Lista de Raças </h1>

<div class="row mb-3">
    <div class="text-end">
        <a asp-action="cadastrar" class="btn btn-primary">Cadastrar</a>

    </div>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <!-- Cabecalho da tabela-->
        <tr>
            <!-- Linhda da tabela -->
            <th>Código</th> <!-- Coluna especifica-->
            <th>Nome</th>
            <th>Espécie</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        <!-- Lugar dos regitros da tabela-->
        @foreach (var raca in Model)
        {
            <tr>
                <!-- Linha -->
            <td>@raca.Id</td> <!-- Coluna especifica para body-->
            <td>@raca.Nome</td>
                <td>@raca.Especie</td>
                <td>
                    <a asp-action="editar" asp-route-id="@raca.Id">Editar</a>
                    <a asp-action="apagar" as-route-id="@raca.Id">Apagar</a>
                </td>
            </tr>
        }

    </tbody>
</table>